### ISSUE TITLE
Fehler im Registrierungsmodul

### ISSUE THREAD

**Issue by Anke** [hschottm/xtmembers#6]
Ich bin mir nicht ganz sicher, ob ich hier richtig bin. Ich habe xt_members, xt_memberfields und registration_extended installiert.

Ich habe im FE-Modul Registrierung ein Häkchen gesetzt vor "Registrierungsmail an Mitglied/Kunde" - nur um den Bereich zu öffnen und mir die Optionen mal anzusehen, d.h. ich habe das Häkchen anschließend wieder weggenommen, weil ich keine Registrierungsmail an Mitglieder schicken will. 

Beim Speichern des Moduls wird mir jetzt allerdings ein Fehler angezeigt, weil ich das (jetzt wieder deaktivierte und somit versteckte) Pflichtfeld "E-Mailtext" nicht ausgefüllt habe.

VG
Anke

**Comment by hschottm** [comment]
Hallo Anke,

das müsstest du leider an Michael Fleischmann, den Entwickler der Erweiterung registration_extended richten. Diese Felder kommen nicht von xtmembers. Ich habe den Fehler übrigens auch.
Kontaktdaten von Michael finde ich in der Erweiterungsbeschreibung allerdings nicht.

LG,
Helmut

**Comment by Anke** [comment]
Danke. Siehe: https://community.contao.org/de/showthread.php?32117-registration_extended-Erweitert-das-Core-Registrierungsmodul&p=409632&viewfull=1#post409632
